import React, { useState } from 'react';
import { PageHeader } from '../components/ui/PageHeader';
import { DOMAIN_LABELS, IncidentClaim } from '../types';

const ACTION_LABEL: Record<string, string> = {
  claim_detected: 'Claim detected',
  claim_merged: 'Duplicate wording merged',
  claim_dropped: 'Claim dropped',
  origin_traced: 'Origin traced',
  spread_predicted: 'Spread predicted',
  narrative_drafted: 'Counter-narrative drafted',
  narrative_no_evidence: 'No evidence found',
  review_required: 'Flagged for human review',
  review_approved: 'Approved by reviewer',
  review_rejected: 'Rejected by reviewer',
  claim_created: 'Claim stored',
  narrative_published: 'Counter-narrative released',
};

const AGENT_FOR: Record<string, string> = {
  claim_detected: 'Claim Detector',
  claim_merged: 'Claim Detector',
  claim_dropped: 'Claim Detector',
  origin_traced: 'Origin Tracer',
  spread_predicted: 'Spread Predictor',
  narrative_drafted: 'Narrative Drafter',
  narrative_no_evidence: 'Narrative Drafter',
  review_required: 'Human review gate',
  review_approved: 'Human reviewer',
  review_rejected: 'Human reviewer',
  narrative_published: 'Human reviewer',
};

export const CounterNarrativePage = ({
  currentIncident,
  handleReviewDecision,
}: {
  currentIncident: IncidentClaim;
  handleReviewDecision: (id: string, approved: boolean) => void;
}) => {
  const [publishState, setPublishState] = useState<'idle' | 'sending' | 'done' | 'error'>('idle');
  const [publishedAt, setPublishedAt] = useState('');
  const [copied, setCopied] = useState(false);

  if (!currentIncident) {
    return <div className="premium-card p-10 text-center text-slate-500">No claim selected.</div>;
  }

  /** Plain-text report: claim, verdict, rebuttal, evidence and audit trail. */
  const buildReport = (inc: IncidentClaim) => {
    const d = inc.detector;
    const cn = inc.ragDrafter?.counterNarrative;
    const srcs = inc.ragDrafter?.sources || [];
    return [
      'COUNTER-NARRATIVE REPORT',
      '='.repeat(62),
      `Claim ID  : ${inc.id}`,
      `Domain    : ${DOMAIN_LABELS[inc.category] ?? inc.category}`,
      `Generated : ${new Date().toISOString()}`,
      '',
      'CLAIM',
      '-'.repeat(62),
      inc.claimText,
      '',
      'ASSESSMENT',
      '-'.repeat(62),
      `Severity   : ${d?.severity ?? 'n/a'}`,
      `Confidence : ${d?.confidence ?? 'n/a'}%`,
      `Reasoning  : ${d?.reasoning ?? 'n/a'}`,
      d?.manipulationTechniques?.length
        ? `Techniques : ${d.manipulationTechniques.join(', ')}`
        : 'Techniques : none recorded',
      '',
      'ORIGIN',
      '-'.repeat(62),
      inc.origin?.summary || 'No provenance recorded.',
      '',
      'COUNTER-NARRATIVE',
      '-'.repeat(62),
      cn?.fullRebuttal || 'Not generated - no supporting evidence retrieved.',
      '',
      `EVIDENCE USED (${srcs.length})`,
      '-'.repeat(62),
      ...(srcs.length ? srcs.map((s, i) => `[${i + 1}] ${s.keyEvidenceQuote}`) : ['None.']),
      '',
      'AUDIT TRAIL',
      '-'.repeat(62),
      ...(inc.auditTrail || []).map(
        (e) => `${e.timestamp?.slice(0, 19) ?? ''}  ${e.action}  ${e.details}`,
      ),
      '',
      '-'.repeat(62),
      'Generated by TruthLens. Machine-assisted analysis, reviewed by a human.',
      'Not an official fact-check. Verify independently before redistribution.',
    ].join('\n');
  };

  const downloadReport = () => {
    const blob = new Blob([buildReport(currentIncident)], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `counter-narrative-${currentIncident.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyNarrative = async () => {
    try {
      await navigator.clipboard.writeText(
        currentIncident.ragDrafter?.counterNarrative.fullRebuttal || '',
      );
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      setCopied(false);
    }
  };

  const publish = async () => {
    setPublishState('sending');
    try {
      const res = await fetch(`/api/claims/${encodeURIComponent(currentIncident.id)}/publish`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ channel: 'internal_register' }),
      });
      if (!res.ok) throw new Error(String(res.status));
      const data = await res.json();
      setPublishedAt(data.published_at || new Date().toISOString());
      setPublishState('done');
    } catch {
      setPublishState('error');
    }
  };

  const narrative = currentIncident.ragDrafter?.counterNarrative;
  const sources = currentIncident.ragDrafter?.sources || [];
  const grounded = !!narrative?.ragConstraintPassed && sources.length > 0;
  const trail = currentIncident.auditTrail || [];
  const review = currentIncident.humanReview.status;
  const decided = review === 'approved' || review === 'rejected';

  return (
    <div className="space-y-8">
      <PageHeader
        kicker="Response"
        title="Counter-Narrative"
        subtitle="Written by the Narrative Drafter using only evidence retrieved from the RAG store at generation time."
      />

      {/* The claim being answered */}
      <div className="premium-card p-6">
        <div className="text-[11px] uppercase tracking-widest text-slate-500 mb-2">Responding to</div>
        <p className="text-lg text-slate-100">“{currentIncident.claimText}”</p>
        <div className="flex flex-wrap gap-4 mt-3 text-[11px] font-mono text-slate-500">
          <span>{currentIncident.id}</span>
          <span>severity {currentIncident.detector?.severity ?? '—'}</span>
          <span>confidence {currentIncident.detector?.confidence ?? '—'}%</span>
          <span>source {currentIncident.ingestion.platform}</span>
        </div>
      </div>

      {/* The generated response */}
      <div className="premium-card p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-bold">Generated response</h2>
          <span className={`text-xs font-bold tracking-widest ${grounded ? 'text-emerald-400' : 'text-amber-300'}`}>
            {grounded ? `GROUNDED IN ${sources.length} SOURCE${sources.length === 1 ? '' : 'S'}` : 'NOT GENERATED'}
          </span>
        </div>

        {grounded ? (
          <p className="text-sm text-slate-200 leading-relaxed">{narrative?.fullRebuttal}</p>
        ) : (
          <div className="text-sm text-amber-300/90 border border-amber-800/50 rounded-md p-4 space-y-2">
            <p className="font-semibold">No counter-narrative was generated for this claim.</p>
            <p className="text-slate-400">
              The Narrative Drafter only writes from evidence it can actually retrieve — it will not
              invent a rebuttal. Nothing in the RAG store was close enough to this claim, so it
              returned <span className="font-mono">no_evidence</span>. Index a relevant fact-check on
              the Evidence page and re-run the claim to produce one.
            </p>
          </div>
        )}
      </div>

      {/* Evidence actually retrieved for THIS claim */}
      <div className="premium-card p-6">
        <div className="flex items-center justify-between mb-1">
          <h2 className="font-bold">Evidence used</h2>
          <span className="text-[11px] font-mono text-slate-500">{sources.length} retrieved</span>
        </div>
        <p className="text-xs text-slate-500 mb-4">
          Pulled from the RAG vector store by semantic similarity at the moment the response was
          written. These are the only facts the drafter was allowed to use.
        </p>
        {sources.length ? (
          <div className="grid md:grid-cols-2 gap-4">
            {sources.map((src) => (
              <div key={src.id} className="rounded-xl border border-slate-800 p-4 bg-slate-950/40">
                <p className="text-sm text-slate-200">{src.keyEvidenceQuote}</p>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-sm text-slate-500">Nothing matched this claim in the RAG store.</p>
        )}
      </div>

      {/* Review decision */}
      <div className="premium-card p-6">
        <h2 className="font-bold mb-1">Human review</h2>
        <p className="text-xs text-slate-500 mb-4">
          Decisions are written to Neo4j as a Review node plus an audit event.
        </p>
        {decided ? (
          <div className={`text-sm font-semibold ${review === 'approved' ? 'text-emerald-400' : 'text-rose-400'}`}>
            {review === 'approved' ? 'Approved' : 'Rejected'}
            {currentIncident.humanReview.reviewedAt ? (
              <span className="text-slate-500 font-normal"> · {currentIncident.humanReview.reviewedAt}</span>
            ) : null}
          </div>
        ) : (
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => handleReviewDecision(currentIncident.id, true)}
              className="px-4 py-2 text-xs font-bold rounded-md bg-emerald-600 text-white"
            >
              Approve
            </button>
            <button
              onClick={() => handleReviewDecision(currentIncident.id, false)}
              className="px-4 py-2 text-xs font-bold rounded-md bg-rose-950 border border-rose-700 text-rose-200"
            >
              Reject
            </button>
          </div>
        )}
      </div>

      {/* Release / export */}
      <div className="premium-card p-6">
        <h2 className="font-bold mb-1">Release</h2>
        <p className="text-xs text-slate-500 mb-4">
          Export the full report, or record a release decision. Available once a reviewer has
          approved a grounded counter-narrative.
        </p>

        {!grounded ? (
          <p className="text-sm text-slate-500">
            Nothing to release — no counter-narrative was generated for this claim.
          </p>
        ) : review !== 'approved' ? (
          <p className="text-sm text-amber-300/90">
            Approve this counter-narrative above before releasing it.
          </p>
        ) : (
          <div className="flex flex-wrap gap-2">
            <button
              onClick={downloadReport}
              className="px-4 py-2 text-xs font-bold rounded-md bg-slate-800 border border-slate-600"
            >
              Download report (.txt)
            </button>
            <button
              onClick={copyNarrative}
              className="px-4 py-2 text-xs font-bold rounded-md bg-slate-800 border border-slate-600"
            >
              {copied ? 'Copied' : 'Copy counter-narrative'}
            </button>
            <button
              onClick={publish}
              disabled={publishState === 'sending' || publishState === 'done'}
              className="px-4 py-2 text-xs font-bold rounded-md bg-cyan-600 text-white disabled:opacity-50"
            >
              {publishState === 'sending'
                ? 'Recording…'
                : publishState === 'done'
                ? 'Release recorded'
                : 'Publish'}
            </button>
          </div>
        )}

        {currentIncident.auditTrail?.some((e) => e.action === 'narrative_published') &&
          publishState !== 'done' && (
            <p className="text-xs text-emerald-400 mt-3">
              Already released — see the audit trail below.
            </p>
          )}
      </div>

      {/* Publish confirmation — states plainly that nothing left the system */}
      {publishState === 'done' && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-sm p-4">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl max-w-lg w-full p-6 space-y-4 shadow-2xl">
            <div className="flex items-start gap-3">
              <span className="text-2xl">✅</span>
              <div>
                <h3 className="text-base font-bold text-white">Release recorded</h3>
                <p className="text-xs text-slate-400 mt-0.5 font-mono">
                  {publishedAt.slice(0, 19).replace('T', ' ')} · channel: internal_register
                </p>
              </div>
            </div>

            <p className="text-sm text-slate-300">
              The decision to release this counter-narrative has been written to Neo4j and added to
              the claim's audit trail.
            </p>

            <div className="rounded-md border border-amber-800/60 bg-amber-950/30 p-3 text-xs text-amber-200">
              <span className="font-bold">Nothing was sent anywhere.</span> No submission was made to
              PIB Fact Check, Sanchar Saathi, any platform, or any other external body — that
              outbound channel is deliberately not wired up. Use “Download report” and submit it
              yourself if you want it to reach someone.
            </div>

            <div className="flex justify-end gap-2 pt-1">
              <button
                onClick={downloadReport}
                className="px-4 py-2 text-xs font-bold rounded-md bg-slate-800 border border-slate-600"
              >
                Download report
              </button>
              <button
                onClick={() => setPublishState('idle')}
                className="px-4 py-2 text-xs font-bold rounded-md bg-cyan-600 text-white"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {publishState === 'error' && (
        <div className="premium-card p-4 border border-rose-800 text-sm text-rose-300">
          Could not record the release — the backend was unreachable.
        </div>
      )}

      {/* Real audit trail from Neo4j */}
      <div className="premium-card p-6">
        <h3 className="text-sm font-bold tracking-widest text-slate-300 mb-1">Audit trail</h3>
        <p className="text-xs text-slate-500 mb-6">{trail.length} events recorded in Neo4j.</p>
        {trail.length === 0 ? (
          <p className="text-sm text-slate-500">No audit events for this claim.</p>
        ) : (
          <div className="space-y-5 border-l border-cyan-500/30 pl-5 ml-2">
            {trail.map((step, i) => (
              <div key={i} className="relative">
                <span className="absolute -left-[27px] top-1.5 w-2.5 h-2.5 rounded-full bg-cyan-400" />
                <div className="text-[11px] font-mono text-slate-500">
                  {step.timestamp?.replace('T', ' ').slice(0, 19) || '—'}
                </div>
                <div className="text-sm text-white font-semibold">
                  {ACTION_LABEL[step.action] || step.action}
                </div>
                <div className="text-xs text-slate-400">
                  {AGENT_FOR[step.action] ? `${AGENT_FOR[step.action]} · ` : ''}
                  {step.details}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
